import type { RoomModel } from "./types"

const exterior = 0.2
const interior = 0.12

export const sampleRoom: RoomModel = {
  version: 1,
  unit: "m",
  wallHeight: 2.4,
  bounds: { width: 10.4, depth: 6.4 },
  spawn: [4.8, 4.6],
  outline: [
    [0, 0],
    [10.4, 0],
    [10.4, 3.4],
    [7.9, 3.4],
    [7.9, 5.0],
    [6.4, 5.0],
    [6.4, 6.4],
    [0, 6.4],
  ],
  walls: [
    { id: "ext-top", a: [0, 0], b: [10.4, 0], thickness: exterior },
    { id: "ext-right", a: [10.4, 0], b: [10.4, 3.4], thickness: exterior },
    {
      id: "ext-room1-bottom",
      a: [10.4, 3.4],
      b: [7.9, 3.4],
      thickness: exterior,
    },
    {
      id: "ext-entry-right",
      a: [7.9, 3.4],
      b: [7.9, 5.0],
      thickness: exterior,
    },
    {
      id: "ext-entry-bottom",
      a: [7.9, 5.0],
      b: [6.4, 5.0],
      thickness: exterior,
    },
    {
      id: "ext-living-right",
      a: [6.4, 5.0],
      b: [6.4, 6.4],
      thickness: exterior,
    },
    { id: "ext-bottom", a: [6.4, 6.4], b: [0, 6.4], thickness: exterior },
    { id: "ext-left", a: [0, 6.4], b: [0, 0], thickness: exterior },

    {
      id: "int-utility-right",
      a: [3.2, 0],
      b: [3.2, 1.6],
      thickness: interior,
    },
    {
      id: "int-master-right",
      a: [3.2, 3.0],
      b: [3.2, 6.4],
      thickness: interior,
    },
    {
      id: "int-utility-bottom",
      a: [0, 1.6],
      b: [3.2, 1.6],
      thickness: interior,
    },
    { id: "int-master-top", a: [0, 3.0], b: [3.2, 3.0], thickness: interior },
    {
      id: "int-boiler-right",
      a: [1.5, 1.6],
      b: [1.5, 3.0],
      thickness: interior,
    },

    { id: "int-bath-left", a: [6.4, 0], b: [6.4, 2.2], thickness: interior },
    { id: "int-entry-left", a: [6.4, 3.4], b: [6.4, 5.0], thickness: interior },
    {
      id: "int-bath-bottom",
      a: [6.4, 2.2],
      b: [7.9, 2.2],
      thickness: interior,
    },
    { id: "int-entry-top", a: [6.4, 3.4], b: [7.9, 3.4], thickness: interior },
    { id: "int-room1-left", a: [7.9, 0], b: [7.9, 3.4], thickness: interior },
  ],
  openings: [
    {
      id: "door-front",
      wallId: "ext-entry-right",
      type: "door",
      from: 0.4,
      to: 1.4,
      bottom: 0,
      top: 2.1,
    },
    {
      id: "door-entry-living",
      wallId: "int-entry-left",
      type: "door",
      from: 0.3,
      to: 1.2,
      bottom: 0,
      top: 2.1,
    },
    {
      id: "door-master",
      wallId: "int-master-right",
      type: "door",
      from: 0.4,
      to: 1.3,
      bottom: 0,
      top: 2.1,
    },
    {
      id: "door-room1",
      wallId: "int-room1-left",
      type: "door",
      from: 2.4,
      to: 3.3,
      bottom: 0,
      top: 2.1,
    },
    {
      id: "door-bath",
      wallId: "int-bath-bottom",
      type: "door",
      from: 0.35,
      to: 1.1,
      bottom: 0,
      top: 2.1,
    },
    {
      id: "door-utility",
      wallId: "int-utility-right",
      type: "door",
      from: 0.4,
      to: 1.2,
      bottom: 0,
      top: 2.1,
    },
    {
      id: "door-boiler",
      wallId: "int-utility-bottom",
      type: "door",
      from: 0.35,
      to: 1.05,
      bottom: 0,
      top: 2.0,
    },
    {
      id: "door-utility-out",
      wallId: "ext-left",
      type: "door",
      from: 5.2,
      to: 6.0,
      bottom: 0,
      top: 2.1,
    },

    {
      id: "win-utility",
      wallId: "ext-top",
      type: "window",
      from: 1.0,
      to: 2.4,
      bottom: 1.1,
      top: 1.9,
    },
    {
      id: "win-kitchen",
      wallId: "ext-top",
      type: "window",
      from: 4.0,
      to: 5.8,
      bottom: 1.0,
      top: 1.9,
    },
    {
      id: "win-bath",
      wallId: "ext-top",
      type: "window",
      from: 6.8,
      to: 7.5,
      bottom: 1.5,
      top: 2.1,
    },
    {
      id: "win-room1-top",
      wallId: "ext-top",
      type: "window",
      from: 8.4,
      to: 9.8,
      bottom: 0.9,
      top: 2.1,
    },
    {
      id: "win-room1-right",
      wallId: "ext-right",
      type: "window",
      from: 0.8,
      to: 2.6,
      bottom: 0.9,
      top: 2.1,
    },
    {
      id: "win-living",
      wallId: "ext-bottom",
      type: "window",
      from: 0.5,
      to: 2.9,
      bottom: 0.4,
      top: 2.1,
    },
    {
      id: "win-master",
      wallId: "ext-bottom",
      type: "window",
      from: 3.8,
      to: 5.8,
      bottom: 0.9,
      top: 2.1,
    },
    {
      id: "win-master-left",
      wallId: "ext-left",
      type: "window",
      from: 0.8,
      to: 2.4,
      bottom: 0.9,
      top: 2.1,
    },
  ],
  rooms: [
    {
      name: "다용도실",
      polygon: [
        [0, 0],
        [3.2, 0],
        [3.2, 1.6],
        [0, 1.6],
      ],
    },
    {
      name: "보일러실",
      polygon: [
        [0, 1.6],
        [1.5, 1.6],
        [1.5, 3.0],
        [0, 3.0],
      ],
    },
    {
      name: "계단",
      polygon: [
        [1.5, 1.6],
        [3.2, 1.6],
        [3.2, 3.0],
        [1.5, 3.0],
      ],
    },
    {
      name: "안방",
      polygon: [
        [0, 3.0],
        [3.2, 3.0],
        [3.2, 6.4],
        [0, 6.4],
      ],
    },
    {
      name: "주방 · 식당",
      polygon: [
        [3.2, 0],
        [6.4, 0],
        [6.4, 2.6],
        [3.2, 2.6],
      ],
    },
    {
      name: "거실",
      polygon: [
        [3.2, 2.6],
        [6.4, 2.6],
        [6.4, 6.4],
        [3.2, 6.4],
      ],
    },
    {
      name: "화장실",
      polygon: [
        [6.4, 0],
        [7.9, 0],
        [7.9, 2.2],
        [6.4, 2.2],
      ],
    },
    {
      name: "복도",
      polygon: [
        [6.4, 2.2],
        [7.9, 2.2],
        [7.9, 3.4],
        [6.4, 3.4],
      ],
    },
    {
      name: "현관",
      polygon: [
        [6.4, 3.4],
        [7.9, 3.4],
        [7.9, 5.0],
        [6.4, 5.0],
      ],
    },
    {
      name: "방1",
      polygon: [
        [7.9, 0],
        [10.4, 0],
        [10.4, 3.4],
        [7.9, 3.4],
      ],
    },
  ],
}
